# Generated by Django 4.2.9 on 2024-02-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('digest', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('lastseen', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=1024)),
                ('completemessage', models.CharField(blank=True, max_length=4096, null=True)),
                ('hostname', models.CharField(max_length=128)),
                ('machineid', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Selinux',
            fields=[
                ('hostname', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('detected', models.DateField()),
                ('updated', models.DateField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('mount', models.CharField(blank=True, max_length=50, null=True)),
                ('rootdir', models.CharField(blank=True, max_length=50, null=True)),
                ('policyname', models.CharField(blank=True, max_length=50, null=True)),
                ('current_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('configured_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('mslstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('memprotect', models.CharField(blank=True, max_length=50, null=True)),
                ('maxkernel', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('preventions', models.CharField(blank=True, max_length=50, null=True)),
                ('messages', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Selinux',
                'verbose_name_plural': 'Selinux',
                'db_table': 'selinux',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='SElinuxEvent',
            fields=[
                ('digest', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128)),
                ('event', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('serial_num', models.IntegerField()),
                ('event_kind', models.CharField(blank=True, max_length=256, null=True)),
                ('session', models.CharField(blank=True, max_length=256, null=True)),
                ('subj_prime', models.CharField(blank=True, max_length=256, null=True)),
                ('subj_sec', models.CharField(blank=True, max_length=256, null=True)),
                ('subj_kind', models.CharField(blank=True, max_length=256, null=True)),
                ('action', models.CharField(blank=True, max_length=256, null=True)),
                ('result', models.CharField(blank=True, max_length=256, null=True)),
                ('obj_prime', models.CharField(blank=True, max_length=256, null=True)),
                ('obj_sec', models.CharField(blank=True, max_length=256, null=True)),
                ('obj_kind', models.CharField(blank=True, max_length=256, null=True)),
                ('how', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'SElinuxEvent',
                'verbose_name_plural': 'SElinuxEvent',
                'db_table': 'selinux_event',
                'ordering': ['date', 'time', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='Setroubleshoot',
            fields=[
                ('digest', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('sealert', models.CharField(max_length=1024)),
                ('firstseen', models.DateField()),
                ('lastseen', models.DateField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Setroubleshoot',
                'verbose_name_plural': 'Setroubleshoot',
                'db_table': 'setroubleshoot',
                'ordering': ['lastseen', 'sealert'],
            },
        ),
        migrations.CreateModel(
            name='SetroubleshootEntry',
            fields=[
                ('CURSOR', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('REALTIMETIMESTAMP', models.BigIntegerField()),
                ('MONOTONICTIMESTAMP', models.BigIntegerField()),
                ('BOOTID', models.CharField(max_length=255)),
                ('PRIORITY', models.IntegerField()),
                ('SYSLOGFACILITY', models.IntegerField()),
                ('SYSLOGIDENTIFIER', models.CharField(max_length=255)),
                ('TRANSPORT', models.CharField(max_length=255)),
                ('PID', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('GID', models.IntegerField()),
                ('COMM', models.CharField(max_length=255)),
                ('EXE', models.CharField(max_length=255)),
                ('CMDLINE', models.TextField()),
                ('CAPEFFECTIVE', models.CharField(max_length=255)),
                ('SELINUXCONTEXT', models.CharField(max_length=255)),
                ('SYSTEMDCGROUP', models.CharField(max_length=255)),
                ('SYSTEMDUNIT', models.CharField(max_length=255)),
                ('SYSTEMDSLICE', models.CharField(max_length=255)),
                ('MACHINEID', models.CharField(max_length=255)),
                ('HOSTNAME', models.CharField(max_length=255)),
                ('CODEFILE', models.CharField(max_length=255)),
                ('CODELINE', models.CharField(max_length=255)),
                ('CODEFUNC', models.CharField(max_length=255)),
                ('MESSAGEID', models.CharField(max_length=255)),
                ('UNIT', models.CharField(max_length=255)),
                ('MESSAGE', models.TextField()),
                ('INVOCATIONID', models.CharField(max_length=255)),
                ('SOURCEREALTIMETIMESTAMP', models.BigIntegerField()),
                ('digest', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Setroubleshoot Entry',
                'verbose_name_plural': 'Setroubleshoot Entries',
            },
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('digest', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('messagedigest', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('snooze', 'Snooze'), ('reject', 'Reject'), ('accept', 'Accept'), ('fixed', 'Fixed')], default='initial', max_length=128)),
                ('solution', models.CharField(max_length=1024)),
                ('hostname', models.CharField(max_length=128)),
                ('lastseen', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
                'db_table': 'suggestion',
            },
        ),
    ]
