# Generated by Django 4.2.9 on 2024-02-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selinux', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selinux',
            new_name='host',
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['hostname'], 'verbose_name': 'host', 'verbose_name_plural': 'hosts'},
        ),
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
    ]
