# Generated by Django 5.0.1 on 2024-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixDataType0',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clock', models.DateTimeField()),
                ('host_name', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ns', models.BigIntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('data_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ZabbixDataType0',
                'verbose_name_plural': 'ZabbixDataType0',
                'db_table': 'zabbixdatatype0',
                'ordering': ['host_name'],
            },
        ),
        migrations.CreateModel(
            name='ZabbixDataType1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clock', models.DateTimeField()),
                ('host_name', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ns', models.BigIntegerField(blank=True, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('data_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ZabbixDataType1',
                'verbose_name_plural': 'ZabbixDataType1',
                'db_table': 'zabbixdatatype1',
                'ordering': ['host_name'],
            },
        ),
        migrations.CreateModel(
            name='ZabbixDataType2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clock', models.DateTimeField()),
                ('host_name', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ns', models.BigIntegerField(blank=True, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('data_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ZabbixDataType2',
                'verbose_name_plural': 'ZabbixDataType2',
                'db_table': 'zabbixdatatype2',
                'ordering': ['host_name'],
            },
        ),
        migrations.CreateModel(
            name='ZabbixDataType3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clock', models.DateTimeField()),
                ('host_name', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ns', models.BigIntegerField(blank=True, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('data_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ZabbixDataType3',
                'verbose_name_plural': 'ZabbixDataType3',
                'db_table': 'zabbixdatatype3',
                'ordering': ['host_name'],
            },
        ),
        migrations.CreateModel(
            name='ZabbixDataType4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clock', models.DateTimeField()),
                ('host_name', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ns', models.BigIntegerField(blank=True, null=True)),
                ('fsname', models.CharField(max_length=512)),
                ('options', models.CharField(blank=True, max_length=512, null=True)),
                ('bytes_used', models.BigIntegerField(blank=True, null=True)),
                ('bytes_free', models.BigIntegerField(blank=True, null=True)),
                ('bytes_total', models.BigIntegerField(blank=True, null=True)),
                ('bytes_pused', models.FloatField(blank=True, null=True)),
                ('bytes_pfred', models.FloatField(blank=True, null=True)),
                ('fstype', models.CharField(blank=True, max_length=24, null=True)),
                ('inodes_used', models.BigIntegerField(blank=True, null=True)),
                ('inodes_free', models.BigIntegerField(blank=True, null=True)),
                ('inodes_total', models.BigIntegerField(blank=True, null=True)),
                ('inodes_pused', models.FloatField(blank=True, null=True)),
                ('inodes_pfree', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ZabbixDataType4',
                'verbose_name_plural': 'ZabbixDataType4',
                'db_table': 'zabbixdatatype4',
                'ordering': ['host_name'],
            },
        ),
    ]
